server:
  port: 8082 # ???Eureka??????
eureka:
  instance:
    prefer-ip-address: true  # ???????IP
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 指定Eureka服务端地址
spring:
  application:
    name: microservice-eureka-house # ??????
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/house_renting?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      view:
        suffix: .html

