server:
  port: 8090 # ???Eureka??????
eureka:
  instance:
    prefer-ip-address: true  # ???????IP
  client:
    service-url:
            defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://192.168.109.134:8761/eureka/
spring:
  application:
    name: microservice-eureka-house # ??????
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/house_renting?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      view:
        suffix: .html

